import { defineField, defineType } from "sanity";

export const food = defineType({
  name: "food",
  title: "Aliment / Plat",
  type: "document",
  fields: [
    defineField({
      name: "name",
      title: "Nom",
      type: "string",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "category",
      title: "Catégorie",
      type: "string",
      options: {
        list: [
          { title: "Viande rouge", value: "red_meat" },
          { title: "Volaille", value: "poultry" },
          { title: "Poisson", value: "fish" },
          { title: "Fruits de mer", value: "seafood" },
          { title: "Fromage", value: "cheese" },
          { title: "Légume", value: "vegetable" },
          { title: "Plat végétarien", value: "vegetarian" },
          { title: "Dessert", value: "dessert" },
          { title: "Charcuterie", value: "charcuterie" },
          { title: "Cuisine du monde", value: "world_cuisine" },
          { title: "Apéritif", value: "aperitif" },
          { title: "Autre", value: "other" },
        ],
      },
    }),
    defineField({
      name: "intensity",
      title: "Intensité du goût",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "fat",
      title: "Gras / richesse",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "salt",
      title: "Salinité",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "sweetness",
      title: "Sucré",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "acidity",
      title: "Acidité du plat",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "spice",
      title: "Épices / piquant",
      type: "number",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "mainIngredients",
      title: "Ingrédients principaux",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "cookingMethods",
      title: "Méthodes de cuisson",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "sauces",
      title: "Sauces / accompagnements",
      type: "array",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "recommendedWineTypes",
      title: "Types de vins recommandés",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: [
          { title: "Rouge", value: "red" },
          { title: "Blanc", value: "white" },
          { title: "Rosé", value: "rose" },
          { title: "Orange", value: "orange" },
          { title: "Effervescent", value: "sparkling" },
          { title: "Fortifié", value: "fortified" },
          { title: "Vin doux", value: "sweet" },
          { title: "Sans alcool", value: "non_alcoholic" },
        ],
      },
    }),
    defineField({
      name: "recommendedGrapes",
      title: "Cépages recommandés",
      type: "array",
      of: [{ type: "reference", to: [{ type: "grape" }] }],
    }),
    defineField({
      name: "recommendedWines",
      title: "Vins recommandés",
      type: "array",
      of: [{ type: "reference", to: [{ type: "wine" }] }],
    }),
    defineField({
      name: "pairingLogic",
      title: "Logique d'accord",
      type: "text",
      rows: 4,
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "array",
      of: [{ type: "block" }],
    }),
  ],
});
