import { defineField, defineType } from "sanity";

export const wine = defineType({
  name: "wine",
  title: "Vin",
  type: "document",
  groups: [
    { name: "identity", title: "Identité" },
    { name: "origin", title: "Origine" },
    { name: "profile", title: "Profil" },
    { name: "purchase", title: "Achat" },
    { name: "editorial", title: "Éditorial" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Nom complet",
      type: "string",
      group: "identity",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "identity",
      options: { source: "title", maxLength: 96 },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: "vintage",
      title: "Millésime",
      type: "number",
      group: "identity",
      validation: (Rule) => Rule.required().min(1800).max(2100),
    }),
    defineField({
      name: "status",
      title: "Statut éditorial",
      type: "string",
      group: "identity",
      initialValue: "draft",
      options: {
        list: [
          { title: "Brouillon", value: "draft" },
          { title: "À réviser", value: "review" },
          { title: "Publié", value: "published" },
          { title: "Archivé", value: "archived" },
        ],
      },
    }),
    defineField({
      name: "mainImage",
      title: "Image principale",
      type: "image",
      group: "identity",
      options: { hotspot: true },
    }),
    defineField({
      name: "gallery",
      title: "Galerie",
      type: "array",
      group: "identity",
      of: [{ type: "image", options: { hotspot: true } }],
    }),
    defineField({
      name: "summary",
      title: "Résumé court",
      type: "text",
      group: "identity",
      rows: 3,
    }),
    defineField({
      name: "description",
      title: "Description complète",
      type: "array",
      group: "identity",
      of: [{ type: "block" }],
    }),

    defineField({
      name: "producer",
      title: "Producteur",
      type: "reference",
      group: "origin",
      to: [{ type: "producer" }],
    }),
    defineField({
      name: "country",
      title: "Pays",
      type: "reference",
      group: "origin",
      to: [{ type: "country" }],
    }),
    defineField({
      name: "region",
      title: "Région",
      type: "reference",
      group: "origin",
      to: [{ type: "region" }],
    }),
    defineField({
      name: "appellation",
      title: "Appellation",
      type: "string",
      group: "origin",
    }),

    defineField({
      name: "color",
      title: "Type de vin",
      type: "string",
      group: "profile",
      options: {
        list: [
          { title: "Rouge", value: "red" },
          { title: "Blanc", value: "white" },
          { title: "Rosé", value: "rose" },
          { title: "Orange", value: "orange" },
          { title: "Effervescent", value: "sparkling" },
          { title: "Fortifié", value: "fortified" },
          { title: "Vin doux", value: "sweet" },
          { title: "Sans alcool", value: "non_alcoholic" },
        ],
      },
    }),
    defineField({
      name: "style",
      title: "Style",
      type: "string",
      group: "profile",
    }),
    defineField({
      name: "grapes",
      title: "Cépages",
      type: "array",
      group: "profile",
      of: [{ type: "reference", to: [{ type: "grape" }] }],
    }),
    defineField({
      name: "culture",
      title: "Culture",
      type: "string",
      group: "profile",
      options: {
        list: [
          { title: "Conventionnelle", value: "conventional" },
          { title: "Biologique", value: "organic" },
          { title: "Biodynamique", value: "biodynamic" },
          { title: "Nature", value: "natural" },
        ],
      },
    }),
    defineField({
      name: "aromas",
      title: "Arômes",
      type: "array",
      group: "profile",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "flavors",
      title: "Saveurs",
      type: "array",
      group: "profile",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "body",
      title: "Corps",
      type: "number",
      group: "profile",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "acidity",
      title: "Acidité",
      type: "number",
      group: "profile",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "tannins",
      title: "Tanins",
      type: "number",
      group: "profile",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "sweetness",
      title: "Sucre",
      type: "number",
      group: "profile",
      validation: (Rule) => Rule.min(1).max(5),
    }),
    defineField({
      name: "alcohol",
      title: "Alcool (%)",
      type: "number",
      group: "profile",
      validation: (Rule) => Rule.min(0).max(25),
    }),
    defineField({
      name: "servingTemperature",
      title: "Température de service",
      type: "string",
      group: "profile",
    }),
    defineField({
      name: "agingPotential",
      title: "Potentiel de garde",
      type: "string",
      group: "profile",
    }),
    defineField({
      name: "finish",
      title: "Finale",
      type: "text",
      group: "profile",
      rows: 3,
    }),

    defineField({
      name: "price",
      title: "Prix",
      type: "number",
      group: "purchase",
    }),
    defineField({
      name: "currency",
      title: "Devise",
      type: "string",
      group: "purchase",
      initialValue: "CAD",
    }),
    defineField({
      name: "format",
      title: "Format",
      type: "string",
      group: "purchase",
      initialValue: "750 ml",
    }),
    defineField({
      name: "availability",
      title: "Disponibilité",
      type: "string",
      group: "purchase",
      options: {
        list: [
          { title: "Disponible", value: "available" },
          { title: "Rupture", value: "out_of_stock" },
          { title: "À venir", value: "coming_soon" },
          { title: "Non suivie", value: "unknown" },
        ],
      },
    }),
    defineField({
      name: "externalCode",
      title: "Code externe / SAQ",
      type: "string",
      group: "purchase",
    }),
    defineField({
      name: "privateImport",
      title: "Importation privée",
      type: "boolean",
      group: "purchase",
      initialValue: false,
    }),

    defineField({
      name: "whyWeLoveIt",
      title: "Pourquoi on l'aime",
      type: "text",
      group: "editorial",
      rows: 4,
    }),
    defineField({
      name: "sommelierTip",
      title: "Conseil du sommelier",
      type: "text",
      group: "editorial",
      rows: 4,
    }),
    defineField({
      name: "occasions",
      title: "Occasions",
      type: "array",
      group: "editorial",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "seasons",
      title: "Saisons",
      type: "array",
      group: "editorial",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "featured",
      title: "Mis en vedette",
      type: "boolean",
      group: "editorial",
      initialValue: false,
    }),

    defineField({
      name: "seoTitle",
      title: "Titre SEO",
      type: "string",
      group: "seo",
    }),
    defineField({
      name: "seoDescription",
      title: "Description SEO",
      type: "text",
      group: "seo",
      rows: 3,
    }),
    defineField({
      name: "ogImage",
      title: "Image OpenGraph",
      type: "image",
      group: "seo",
      options: { hotspot: true },
    }),
  ],
  preview: {
    select: {
      title: "title",
      vintage: "vintage",
      media: "mainImage",
    },
    prepare({ title, vintage, media }) {
      return {
        title,
        subtitle: vintage ? String(vintage) : "Sans millésime",
        media,
      };
    },
  },
});
